package com.mpp.instagram.profile.entity;

import org.springframework.data.cassandra.core.mapping.Column;
import org.springframework.data.cassandra.core.mapping.PrimaryKey;
import org.springframework.data.cassandra.core.mapping.Table;

import java.io.Serializable;

@Table("INSTAGRAM_PROFILE")
public class ProfileEntity implements Serializable {

    private long id;    //AutoGenerated ID
    @Column("user_name")
    @PrimaryKey
    private String username;  //Storing UserName
    @Column("profile_image")
    private String profile_image;  //Storing Profile image for the user
    @Column("post_counter")
    private int post_counter;     //Storing the counter of posts
    @Column("followers_counter")
    private int followers_counter;  // Storing the counter of followers
    @Column("following_counter")
    private int following_counter;  // Storing the counter of followings
    @Column("bio")
    private String bio;  // Storing the user biography

    public ProfileEntity(String username) {
        this.username = username;
    }

    public ProfileEntity(String username, String profile_image, int post_counter, int followers_counter, int following_counter, String bio) {
        this.username = username;
        this.profile_image = profile_image;
        this.post_counter = post_counter;
        this.followers_counter = followers_counter;
        this.following_counter = following_counter;
        this.bio = bio;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getProfile_image() {
        return profile_image;
    }

    public void setProfile_image(String profile_image) {
        this.profile_image = profile_image;
    }

    public int getPost_counter() {
        return post_counter;
    }

    public void setPost_counter(int post_counter) {
        this.post_counter = post_counter;
    }

    public int getFollowers_counter() {
        return followers_counter;
    }

    public void setFollowers_counter(int followers_counter) {
        this.followers_counter = followers_counter;
    }

    public int getFollowing_counter() {
        return following_counter;
    }

    public void setFollowing_counter(int following_counter) {
        this.following_counter = following_counter;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    @Override
    public String toString() {
        return "ProfileEntity{" +
                "username='" + username + '\'' +
                ", profile_image='" + profile_image + '\'' +
                ", post_counter=" + post_counter +
                ", followers_counter=" + followers_counter +
                ", following_counter=" + following_counter +
                ", bio='" + bio + '\'' +
                '}';
    }
}
