package com.mpp.instagram.profile.entity;

import org.springframework.data.cassandra.core.mapping.Column;
import org.springframework.data.cassandra.core.mapping.PrimaryKey;
import org.springframework.data.cassandra.core.mapping.Table;

import java.io.Serializable;

//@Table("INSTAGRAM_USER")
public class ProfileEntity {//implements Serializable {
//
//        private long id;    //AutoGenerated ID
//        @Column("user_name")
//        @PrimaryKey
//        private String username;  //Storing UserName
//        @Column("profile_image")
//        private String profile_image;  //Storing Profile image for the user
//        @Column("post_counter")
//        private String post_counter;     //Storing the counter of posts
//        @Column("followers_counter")
//        private String followers_counter;  // Storing the counter of followers
//        @Column("followers_counter")
//        private String following_counter;  // Storing the counter of followings



}
