package com.mpp.instagram.Models;

import org.springframework.data.cassandra.core.mapping.Column;
import org.springframework.data.cassandra.core.mapping.PrimaryKey;

import java.util.List;

public class Profile {

    private int id;    //AutoGenerated ID
    //@Column("user_name")
    //@PrimaryKey
    private String username;  //Storing UserName
    //@Column("profile_image")
    //private String profile_image;  //Storing Profile image for the user
    //@Column("post_counter")
    private int post_counter;     //Storing the counter of posts
    //@Column("followers_counter")
    private int followers_counter;  // Storing the counter of followers
    //@Column("following_counter")
    private int following_counter;  // Storing the counter of followings
    //@Column("bio")
    private String bio;  // Storing the user biography

    private List<User> friends;

//    public Profile(String username) {
//        this.username = username;
//    }

    public Profile(int id, String username, int post_counter, int followers_counter, int following_counter, String bio, List<User> friends) {
        this.id = id;
        this.username = username;
        //this.profile_image = profile_image;
        this.post_counter = post_counter;
        this.followers_counter = followers_counter;
        this.following_counter = following_counter;
        this.bio = bio;
        this.friends = friends;
    }

    public int getId() { return id; }

    public void setId(int id) { this.id = id; }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

//    public String getProfile_image() {
//        return profile_image;
//    }
//
//    public void setProfile_image(String profile_image) {
//        this.profile_image = profile_image;
//    }

    public int getPost_counter() {
        return post_counter;
    }

    public void setPost_counter(int post_counter) {
        this.post_counter = post_counter;
    }

    public int getFollowers_counter() {
        return followers_counter;
    }

    public void setFollowers_counter(int followers_counter) {
        this.followers_counter = followers_counter;
    }

    public int getFollowing_counter() {
        return following_counter;
    }

    public void setFollowing_counter(int following_counter) {
        this.following_counter = following_counter;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    public List<User> getFriends() { return friends; }

    public void setFriends(List<User> friends) { this.friends = friends; }

    @Override
    public String toString() {
        return "ProfileEntity{" +
                "username='" + username + '\'' +
                //", profile_image='" + profile_image + '\'' +
                ", post_counter=" + post_counter +
                ", followers_counter=" + followers_counter +
                ", following_counter=" + following_counter +
                ", bio='" + bio + '\'' +
                '}';
    }
}
